version: "3"
services:
  app:
    image: php:7.4-fpm
    volumes:
    - ./src:/app
    working_dir: /app
  loadbalancer:
    image: nginx
    volumes:
    - ./src/public:/app/public
    - ./conf/nginx/app.conf.template:/etc/nginx/templates/default.conf.template
    ports:
    - 80:80
    environment:
      FASTCGI_PASS: app:9000
