version: "3"
services:
  app:
    image: php:7.4-fpm
    volumes:
    - ./src:/app
    working_dir: /app
  loadbalancer:
    image: nginx
    volumes:
    - ./src/public:/app/public
    - ./conf/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
  