apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: example-php-project
build:
  artifacts:
  - image: localhost:32000/app-frontend
    docker:
      dockerfile: Dockerfile-frontend
  - image: localhost:32000/app-loadbalancer
    docker:
      dockerfile: Dockerfile-loadbalancer
deploy:
  kustomize:
    paths:
    - kustomize/base
profiles:
- name: local
  deploy:
    kubeContext: microk8s
    kustomize:
      paths:
      - kustomize/overlays/local
