apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: example-php-project
build:
  artifacts:
  - image: app-backend
    docker:
      dockerfile: Dockerfile-backend
  - image: app-loadbalancer
    docker:
      dockerfile: Dockerfile-loadbalancer
deploy:
  kustomize:
    paths:
    - kustomize/base
profiles:
- name: local
  deploy:
    kustomize:
      paths:
      - kustomize/overlays/local
