apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: localhost:32000/app-frontend
        name: app-frontend
        ports:
        - containerPort: 9000
        resources: {}
      - image: localhost:32000/app-loadbalancer
        name: app-loadbalancer
        ports:
        - containerPort: 80
        resources: {}
        env:
          - name: FASTCGI_PASS
            value: "127.0.0.1:9000"
status: {}
