apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: app-backend
        name: app-backend
        resources: {}
      - image: app-loadbalancer
        name: app-loadbalancer
        resources: {}
        ports:
        - containerPort: 80
        env:
        - name: FASTCGI_PASS
          value: "127.0.0.1:9000"
status: {}
